[[headers]]
for = "/*"
[headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Link = [
    "</main.css>; rel=preload; as=style",
    "</main.js>; rel=preload; as=script"
    ]